baseurl = "/"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
languageCode = "en-us"
languageLang = "en"
title = "Homepage"
[[menu.main]]
name = "Category"
url = "category"
weight = "5"
[[menu.main]]
name = "Products"
url = "/products"
weight = "1"
[[menu.main]]
name = "Values"
url = "/values"
weight = 2
[[menu.main]]
name = "Blog"
url = "/post"
weight = "3"
[[menu.main]]
name = "Contact"
url = "/contact"
weight = "4"
