---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: site/content/values
  label: Values
  create: all
  match: "**/*"
- type: directory
  path: site/content/products
  label: Products
  create: all
  match: "**/*"
- type: directory
  path: site/content/post
  label: Post
  create: all
  match: "**/*"
- type: directory
  path: site/content/contact
  label: Contact
  create: all
  match: "**/*"
- type: document
  path: site/config.toml
  label: Config
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  install_dependencies_command: yarn build
  preview_docker_image: forestryio/hugo:node12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn preview:webpack
version: 0.81.0
